### ISSUE TITLE
unitCell.py

### ISSUE THREAD

**Issue by VivekUUnni** [dschick/udkm1Dsim#1]
Its possible to initialise most of the properties of unitCell by "self.property = x".
Here property stands for the keyword for a particular property and x is the value.

The properties like thermal conductivity,linear thermal expansion, heat capacity and subsystem coupling  can be initialised this way.But while printing the properties using string class it prints the default value '0' and not the initialised values as printing is done by the string representation.

**Comment by dschick** [comment]
I guess the init method overwrites the values as you set them
