### ISSUE TITLE
Handling of incorrect form factor paths

### ISSUE THREAD

**Issue by EmCeBeh** [dschick/udkm1Dsim#100]
When creating and atom and providing a `form_factor_path` to a non-existing file, there is a message saying the file was not found, but python additionally throws a cryptic expression of the variable `f` being referenced before asignment.

The return statement for `f` is not part of the `try - except` block, thus the error message. Is this intended / usually handled?

https://github.com/dschick/udkm1Dsim/blob/6f8d2199b26ed62ec196acf7fdef722c0b097683/udkm1Dsim/structures/atoms.py#L171-L177

Thanks

**Comment by dschick** [comment]
fixed with 43c5d0b
