### ISSUE TITLE
An error while calculating backside excitation

### ISSUE THREAD

**Issue by Serj-R** [dschick/udkm1Dsim#150]
![image](https://github.com/dschick/udkm1Dsim/assets/105922525/966ecb89-6822-4961-9584-8be3e8ba86ca)

Hi,

https://udkm1dsim.readthedocs.io/en/latest/examples/heat.html
in this code there is an error while trying calculating the backside excitation

**Comment by dschick** [comment]
I guess you have installed the toolbox from `pypi` using `pip install udkm1Dsim`?

if so, please do an upgrade `pip install --upgrade udkm1Dsim` since I have not rebuilt the package in long time.

**Comment by Serj-R** [comment]
Yes, now it works! Thank you!
