### ISSUE TITLE
add possibility to provide combined atomic and magnetic form factors for AtomMixed type structure

### ISSUE THREAD

**Issue by tox1c90** [dschick/udkm1Dsim#76]
It should be possible to provide combined atomic and magnetic form factors for an `AtomMixed` type structure object. This becomes particularly important in case of using experimentally obtained form factors that were not measured individually for each type of atom but for a whole layer or alloy consisting of more than one element.

**Comment by dschick** [comment]
thanks for pointing that out!

I guess it is straight forward to implement that.
So in case an `atomic_form_factor_path` or  `magnetic_form_factor_path` is given for the `AtomMixed` these values will be used.
The fallback will be the averaging of the individualt form factors of the `Atom`s as it is done now.

**Comment by dschick** [comment]
Hi @tox1c90 , could you please check #77 if it solves the issue?

**Comment by dschick** [comment]
solved by #77
