### ISSUE TITLE
Problem with N-temperature model and thermal conductivity

### ISSUE THREAD

**Issue by theodoho** [dschick/udkm1Dsim#80]
Hi,

I'm trying to build a 2T-model where the electronic thermal conductivity is proportional to the ratio between the electron and lattice temperatures. However, this gives an indexing error. Is there a way around this?

![image](https://user-images.githubusercontent.com/36757786/111440815-03034980-8707-11eb-8a28-1389db0f01a9.png)
![image](https://user-images.githubusercontent.com/36757786/111440938-1dd5be00-8707-11eb-93df-c04904b77841.png)
![image](https://user-images.githubusercontent.com/36757786/111441024-3219bb00-8707-11eb-95b7-76b5b83b1014.png)

**Comment by dschick** [comment]
Hi, this problem is already addressed in #70 
It is actually not a big problem to allows to access all subsystem temperatures also in the `thermal_conductivity`, since this is already done in the `sub_system_ coupling`.
It is more an issue of backwards compatibility and simplicity e.g. for 1TM.

I would like to think of a way to automatically detect if the temperature is input as a scalar (only current subsystem) or as a vector (also accessing other subsystems)

**Comment by theodoho** [comment]
Got it. 

I've noticed that some models assume ke=k0= constant. 

I think I'll use a constant value for Tl in the meantime then (e.g. the average).

**Comment by dschick** [comment]
I just created a PR #81 
You could try test it and if it is working fine, I ccan merge it

**Comment by theodoho** [comment]
This seems to work as far as I can tell. Thank you. :)

**Comment by dschick** [comment]
Great, could you confirm, that it is working for both cases: scalar vs vectorized temperature dependence?

I would also guess, that it might cost a bit of computational time, since I catched an exception at a very low level of the ode-solver.
Maybe you could also compare the computational time for the current development branch vs this fix?

**Comment by theodoho** [comment]
It seems to work for both cases, and the computational time is similar.

**Comment by dschick** [comment]
I confirm that it is working.
I am closing this one. Please follow my comments in #81

**Comment by AleksUDKM** [comment]
I need to dig up  this closed issue, because it does not work for me.
Could you please provide an example code how it should work? 

When I put for example the line 
`SRO.therm_cond = ['lambda T: (91-9.6)*(T[0]/T[1])', 5.72*u.W/(u.m*u.K)]`
in the example code provided in the documentation for the N-Temperature model I get the error message

![grafik](https://user-images.githubusercontent.com/36692180/145113926-8490d384-3cfd-4612-b3b6-f363a3ecb57d.png)

The full code that I am running goes like this
```
# -*- coding: utf-8 -*-
"""
Created on Tue Dec  7 22:19:11 2021

@author: Aleks
"""

import udkm1Dsim as ud
u = ud.u  
import numpy as np
import matplotlib.pyplot as plt
u.setup_matplotlib()  


O = ud.Atom('O')
Ti = ud.Atom('Ti')
Sr = ud.Atom('Sr')
Ru = ud.Atom('Ru')
Pb = ud.Atom('Pb')
Zr = ud.Atom('Zr')

# c-axis lattice constants of the two layers
c_STO_sub = 3.905*u.angstrom
c_SRO = 3.94897*u.angstrom
# sound velocities [nm/ps] of the two layers
sv_SRO = 6.312*u.nm/u.ps
sv_STO = 7.800*u.nm/u.ps

# SRO layer
prop_SRO = {}
prop_SRO['a_axis'] = c_STO_sub  # aAxis
prop_SRO['b_axis'] = c_STO_sub  # bAxis
prop_SRO['deb_Wal_Fac'] = 0  # Debye-Waller factor
prop_SRO['sound_vel'] = sv_SRO  # sound velocity
prop_SRO['opt_ref_index'] = 2.44+4.32j
prop_SRO['therm_cond'] = 5.72*u.W/(u.m*u.K)  # heat conductivity
prop_SRO['lin_therm_exp'] = 1.03e-5  # linear thermal expansion
prop_SRO['heat_capacity'] = '455.2 + 0.112*T - 2.1935e6/T**2'  # heat capacity [J/kg K]

SRO = ud.UnitCell('SRO', 'Strontium Ruthenate', c_SRO, **prop_SRO)
SRO.add_atom(O, 0)
SRO.add_atom(Sr, 0)
SRO.add_atom(O, 0.5)
SRO.add_atom(O, 0.5)
SRO.add_atom(Ru, 0.5)

# STO substrate
prop_STO_sub = {}
prop_STO_sub['a_axis'] = c_STO_sub  # aAxis
prop_STO_sub['b_axis'] = c_STO_sub  # bAxis
prop_STO_sub['deb_Wal_Fac'] = 0  # Debye-Waller factor
prop_STO_sub['sound_vel'] = sv_STO  # sound velocity
prop_STO_sub['opt_ref_index'] = 2.1+0j
prop_STO_sub['therm_cond'] = 12*u.W/(u.m*u.K)  # heat conductivity
prop_STO_sub['lin_therm_exp'] = 1e-5  # linear thermal expansion
prop_STO_sub['heat_capacity'] = '733.73 + 0.0248*T - 6.531e6/T**2'  # heat capacity [J/kg K]

STO_sub = ud.UnitCell('STOsub', 'Strontium Titanate Substrate', c_STO_sub, **prop_STO_sub)
STO_sub.add_atom(O, 0)
STO_sub.add_atom(Sr, 0)
STO_sub.add_atom(O, 0.5)
STO_sub.add_atom(O, 0.5)


# update the relevant thermo-elastic properties of the layers in the sample structure
SRO.therm_cond = ['lambda T: (91-9.6)*(T[0]/T[1])',
                  5.72*u.W/(u.m*u.K)]
SRO.lin_therm_exp = [1.03e-5,
                     1.03e-5]
SRO.heat_capacity = ['0.112*T',
                     '455.2 - 2.1935e6/T**2']
SRO.sub_system_coupling = ['5e17*(T_1-T_0)',
                           '5e17*(T_0-T_1)']



STO_sub.therm_cond = [0,
                      12*u.W/(u.m*u.K)]
STO_sub.lin_therm_exp = [1e-5,
                         1e-5]
STO_sub.heat_capacity = ['0.0248*T',
                         '733.73 - 6.531e6/T**2']
STO_sub.sub_system_coupling = ['5e17*(T_1-T_0)',
                               '5e17*(T_0-T_1)']


S = ud.Structure('Single Layer')
S.add_sub_structure(SRO, 100)  # add 100 layers of SRO to sample
S.add_sub_structure(STO_sub, 200)  # add 200 layers of STO substrate


#%%

# when calculating the laser absorption profile using Lamber-Beer-law
# the opt_pen_depth must be set manually or calculated from the refractive index
SRO.set_opt_pen_depth_from_ref_index(800*u.nm)
STO_sub.set_opt_pen_depth_from_ref_index(800*u.nm)

# temporal and spatial grid
delays = np.r_[-5:15:0.01]*u.ps
_, _, distances = S.get_distances_of_layers()




#%%
h = ud.Heat(S, True)

h.save_data = False
h.disp_messages = True


# enable heat diffusion
h.heat_diffusion = True
# set the boundary conditions
h.boundary_conditions = {'top_type': 'isolator', 'bottom_type': 'isolator'}


h.excitation = {'fluence': [5]*u.mJ/u.cm**2,
                'delay_pump':  [0]*u.ps,
                'pulse_width':  [0.25]*u.ps,
                'multilayer_absorption': True,
                'wavelength': 800*u.nm,
                'theta': 45*u.deg}

h.boundary_conditions = {'top_type': 'isolator', 'bottom_type': 'isolator'}


plt.figure()
dAdz, _, _, _ = h.get_multilayers_absorption_profile()
plt.plot(distances.to('nm'), dAdz, label='multilayer')
dAdz = h.get_Lambert_Beer_absorption_profile()
plt.plot(distances.to('nm'), dAdz, label='Lamber-Beer')
plt.legend()
plt.xlabel('Distance [nm]')
plt.ylabel('Differnetial Absorption')
plt.title('Laser Absorption Profile')
plt.show()



# The resulting temperature profile is calculated in one line:
temp_map, delta_temp = h.get_temp_map(delays, 300*u.K)

#%%
plt.figure(figsize=[6, 8])
plt.subplot(2, 1, 1)
plt.pcolormesh(distances.to('nm').magnitude, delays.to('ps').magnitude, temp_map[:, :, 0], shading='auto')
plt.colorbar()
plt.xlabel('Distance [nm]')
plt.ylabel('Delay [ps]')
plt.title('Temperature Map Electrons')

plt.subplot(2, 1, 2)
plt.pcolormesh(distances.to('nm').magnitude, delays.to('ps').magnitude, temp_map[:, :, 1], shading='auto')
plt.colorbar()
plt.xlabel('Distance [nm]')
plt.ylabel('Delay [ps]')
plt.title('Temperature Map Phonons')

plt.tight_layout()
plt.show()
```

**Comment by AvonReppert** [comment]
I was just confused. 
For this  to work I needed to update udkm1Dsim from 1.5.0  to version 1.5.3 via github via
`pip install git+https://github.com/dschick/udkm1Dsim.git`

And then this fieature works:

```
SRO.therm_cond = ['lambda T: (91-9.6)*(T_0/T_1)',
                  5.72*u.W/(u.m*u.K)]
```
Thanks for implementing it

**Comment by theodoho** [comment]
Glad to hear you found the issue! :)

/Theodor

**Comment by dschick** [comment]
Hi @AleksUDKM,

thanks for comming back to this issue.
I guess it is not too well documented and the current implementation can lead to some confusions, despite of your version conflict.

Actually, I spend quite some time with thinking about the optimal nomenclature of this feature, as some properties require only one and others all `sub_system` temperatures.
I also wanted to avoid breaking the backwards compatibility with older scripts, e.g. by forcing the user to always use the indices `_N`, or to overcomplicate it.
Finally, some of the properties must be also analytically integratable by `sympy` which makes things even more complex.

Right now, I try to catch different versions directly in the `odefunc` of the `heat` class, which is not too smart.
I guess it would be better to internally use always the indexing `_N` but to allow also for the old indexing style `[N]` as well as no indexing at all (only use current `sub_system` temperature) within the user interface.

Let me check if I can go for something in this direction.

**Comment by dschick** [comment]
I am closing it for now, but please reopen, if you encounter any further issues.
