### ISSUE TITLE
Temperature dependence of electron-phonon coupling factor

### ISSUE THREAD

**Issue by theodoho** [dschick/udkm1Dsim#82]
The electron-phonon coupling factor depends on the electron temperature [1,2]. In the [documentation](https://udkm1dsim.readthedocs.io/en/latest/heat.html#udkm1Dsim.simulations.heat.Heat.calc_heat_diffusion) and the [examples](https://udkm1dsim.readthedocs.io/en/latest/examples/heat.html#N-Temperature-Model) it seems like a constant value is used (5e17 W/(m3 K) for SRO and STO).

Maybe the documentation should mention that G can vary with Te? This can easily be implemented by using the data in [2].

[1] [https://journals.aps.org/prb/abstract/10.1103/PhysRevB.77.075133](https://journals.aps.org/prb/abstract/10.1103/PhysRevB.77.075133)
[2] [https://faculty.virginia.edu/CompMat/electron-phonon-coupling/](https://faculty.virginia.edu/CompMat/electron-phonon-coupling/)

**Comment by dschick** [comment]
okay, thanks for pointing this out.
I guess one should find a compromise between showing all possibilities and do not over-complicating things for beginners.

In my opinion the documenation is okay for that: stating that "G_i(T_1,...,T_N)" is a function of all sub-system-temperatures.
For the example I would only make a general statement.

Maybe you can draft a PR?

**Comment by theodoho** [comment]
I can do that. :)

**Comment by dschick** [comment]
solved with #83
