### ISSUE TITLE
Wrong spring constants (integer)

### ISSUE THREAD

**Issue by rshayduk** [dschick/udkm1Dsim#86]
St.get_layer_property_vector('spring_const') yields array of integers, so all spring constants are, apparently, wrong, i.e. rounded resulting in all simulations yielding wrong dynamics. Since spring constants are in the range between 1 and 10, typically 5, it is hard to notice, because 5.2, for example, rounds to 5, and sound speeds would be off not so much.

This is my hypothesis, but try to find eigenfrequencies for crystal any structure and elements, but put some large lattice constant, like 10 angstrom and low sound speed, like 1km/s to get low stiffness. The output from Structure is zero spring constants, therefore zero frequencies from eigenproblem etc. independent on which structure or chemistry of unit cell one defines. Because all rounds to zero.

**Comment by rshayduk** [comment]
May be the problem is in the Layer class here: "self.spring_const = np.array([0])"

May be that zero makes it of type int. May be we need to:

self.spring_const = np.array([0], dtype="double") or something

**Comment by dschick** [comment]
very good catch @rshayduk !

could check if #87 fixes this issue completely?

**Comment by dschick** [comment]
fixed by #87
