### ISSUE TITLE
Use numpy functions in layer properties

### ISSUE THREAD

**Issue by dschick** [dschick/udkm1Dsim#88]
currently it is not easily possible to use numpy function, such as `np.exp` in layer properties such as the `heat_capacity`.
The reason is the automatic integration of the `heat_capacity` and `lin_therm_exp` using `SymPy`.
For that, one need to define the lambda function with a bare `exp` to make the integration work in.
Unfortunately, the expression is evaluated using `numpy` which would require a `np.exp` e.g. in the `heat` class.

For now, one can define the `heat_capacity` with the `numpy` prefix and do the integration by hand and set the `int_heat_capacity` manually.

A future solution would be a list of math functions, which are automatically prefixed with `np.` or are directly imported in the according classes, e.g. by
`import exp, ln, log from numpy`

**Comment by pgaal** [comment]
Thanks' Daniel, very helpful... I used the future solution by defining the lambda function for the heat capacity using exp() and by importing exp from numpy in the layer class. This seems to work for now

**Comment by dschick** [comment]
Hi @pgaal ,

could you please checkout #90 if this works fine for you as well?

**Comment by pgaal** [comment]
Hä, wat soll ich machen?


Dr. Peter Gaal
Gruppenleiter Röntgenoptik
Anwendungswissenschaften/Kristalline Materialien für Photonik
T: +49 (0)30 6392 2858
F: +49 (0)30 6392 3003
E: ***@***.******@***.***>
Leiter des IKZ-DESY JointLab Hamburg Bahrenfeld

***@***.***
LEIBNIZ-INSTITUT
FÜR KRISTALLZÜCHTUNG
im Forschungsverbund Berlin e.V

Max-Born-Straße 2
12489 Berlin
www.ikz-berlin.de<https://www.ikz-berlin.de/>

________________________________

Diese Nachricht enthält vertrauliche Informationen und ist nur für die genannten Empfänger bestimmt. Falls Sie kein genannter Empfänger sind, dürfen Sie diese E-Mail nicht verbreiten, verteilen oder kopieren. Bitte benachrichtigen Sie ***@***.*** umgehend per E-Mail, falls Sie diese E-Mail fälschlicherweise erhalten haben, und löschen Sie sie von lhrem System. Eine sichere und fehlerfreie E-Mail-Übertragung kann nicht gewährleistet werden, da Informationen abgefangen, beschädigt, zerstört, verzögert werden, verloren gehen, unvollständig sein oder Viren enthalten können. Aus diesem Grund übernimmt  keine Haftung für jedwede Fehler oder Auslassungen in dieser Nachricht, die auf eine E-Mail-Übertragung zurückzuführen sind. Falls eine Bestätigung erforderlich ist, fordern Sie bitte eine gedruckte Version an.

Von: Daniel Schick ***@***.***
Gesendet: Donnerstag, 8. Juli 2021 14:53
An: dschick/udkm1Dsim ***@***.***>
Cc: Gaal, Dr. Peter ***@***.***>; Mention ***@***.***>
Betreff: Re: [dschick/udkm1Dsim] Use numpy functions in layer properties (#88)


Hi @pgaal<https://github.com/pgaal> ,

could you please checkout #89<https://github.com/dschick/udkm1Dsim/pull/89> if this works fine for you as well?

**Comment by dschick** [comment]
fixed by #90
